name: Deploy App to EC2

on:
  workflow_run:
    workflows: ["Docker Image CI for GitHub Container registry"]
    types:
      - completed
  # push:
  #   branches:
  #     - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_KEY }}

      - name: Pull docker    
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} << 'EOF'
            echo ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd /home/ec2-user/docker
            sudo echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env
            sudo echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            sudo echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            sudo echo "DB_DBNAME=${{ secrets.DB_DBNAME }}" >> .env
            sudo docker-compose down
            sudo docker pull ghcr.io/ivansu995/praksa:latest
            sudo docker-compose up -d
          EOF