name: Nginx Proxy Docker Image CI for GitHub Container registry

on:
  push:
    branches:
      - docker-build

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build ./nginx/Dockerfile --tag ghcr.io${{ github.repostiroy_owner }}/nginx-proxy:latest
      
      - name: Push docker image
        run: |
          docker push ghcr.io${{ github.repostiroy_owner }}/nginx-proxy:latest
